# Generated by Django 4.2 on 2025-11-13 20:01

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ("commandcenter", "0037_branding_updates"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenAIConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enable",
                    models.BooleanField(
                        default=False,
                        help_text="Enable to allow CyberWriter to query the OpenAI Assistants API",
                    ),
                ),
                (
                    "assistant_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="OpenAI Assistant identifier to process remediation prompts",
                        max_length=255,
                    ),
                ),
                (
                    "api_key",
                    django_cryptography.fields.encrypt(
                        models.CharField(
                            blank=True,
                            default="",
                            help_text="API key used to authenticate with OpenAI",
                            max_length=255,
                        )
                    ),
                ),
            ],
            options={
                "verbose_name": "OpenAI Configuration",
            },
        ),
    ]
