# Generated by Django 3.2.19 on 2025-02-07 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rolodex', '0052_projectobjective_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='data_responses',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Responses collected from the dynamic reporting data form',
                verbose_name='Dynamic Data Responses',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='workbook_data',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Parsed workbook data used to dynamically generate reporting questions',
                verbose_name='Workbook Data',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='workbook_file',
            field=models.FileField(
                blank=True,
                help_text='Upload the JSON workbook that will be used to drive reporting questions',
                null=True,
                upload_to='project_workbooks/',
                verbose_name='Workbook',
            ),
        ),
        migrations.CreateModel(
            name='ProjectDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to='project_data/', verbose_name='Supporting Data File')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to='rolodex.project')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'verbose_name': 'Project data file',
                'verbose_name_plural': 'Project data files',
            },
        ),
    ]
