# Generated by ChatGPT

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rolodex", "0054_projectdatafile_requirements"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="data_artifacts",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Parsed supporting data derived from uploaded artifacts",
            ),
        ),
    ]
