# Generated by Django 4.2 on 2025-11-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rolodex", "0055_project_data_artifacts"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="risks",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Risk ratings derived from the uploaded workbook",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="data_responses",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Responses collected from the dynamic reporting data form",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="workbook_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Parsed workbook data used to dynamically generate reporting questions",
            ),
        ),
    ]
