# Generated by Django 4.2 on 2025-11-04 01:30

from django.db import migrations


def backfill_project_risks(apps, schema_editor):
    from ghostwriter.rolodex import risk

    risk.backfill_missing_project_risks(using=schema_editor.connection.alias)


class Migration(migrations.Migration):
    dependencies = [
        ("rolodex", "0056_project_risks_alter_project_data_responses_and_more"),
        ("reporting", "0060_graderiskmapping"),
    ]

    operations = [
        migrations.RunPython(backfill_project_risks, migrations.RunPython.noop),
    ]
