# Generated by ChatGPT

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rolodex", "0062_general_cap_mappings"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="cap",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Corrective action plan values derived from workbook responses and supporting data",
            ),
        ),
    ]
