# Generated by ChatGPT

from django.db import migrations


def populate_project_cap_from_responses(apps, schema_editor):
    Project = apps.get_model("rolodex", "Project")

    for project in Project.objects.exclude(data_responses=None).iterator():
        responses = project.data_responses or {}
        if not isinstance(responses, dict):
            continue

        cap_payload = dict(project.cap or {})
        updated = False

        password_section = responses.get("password")
        if isinstance(password_section, dict):
            password_cap_section = {}

            cap_fields = password_section.get("policy_cap_fields")
            if isinstance(cap_fields, list) and cap_fields:
                password_cap_section["policy_cap_fields"] = list(cap_fields)

            cap_context = password_section.get("policy_cap_context")
            if isinstance(cap_context, dict) and cap_context:
                password_cap_section["policy_cap_context"] = dict(cap_context)

            cap_map = password_section.get("policy_cap_map")
            if isinstance(cap_map, dict) and cap_map:
                password_cap_section["policy_cap_map"] = {
                    domain: dict(values)
                    for domain, values in cap_map.items()
                    if isinstance(values, dict) and values
                }

            cap_entries = []
            entries = password_section.get("entries")
            if isinstance(entries, list):
                for entry in entries:
                    if not isinstance(entry, dict):
                        continue
                    domain_value = entry.get("domain") or entry.get("name")
                    domain = str(domain_value).strip() if domain_value else ""
                    if not domain:
                        continue
                    policy_values = entry.get("policy_cap_values")
                    if isinstance(policy_values, dict) and policy_values:
                        cap_entries.append(
                            {"domain": domain, "policy_cap_values": dict(policy_values)}
                        )

            if cap_entries:
                password_cap_section["entries"] = cap_entries

            if password_cap_section:
                if cap_payload.get("password") != password_cap_section:
                    cap_payload["password"] = password_cap_section
                    updated = True
            elif "password" in cap_payload:
                cap_payload.pop("password", None)
                updated = True

        dns_section = responses.get("dns")
        if isinstance(dns_section, dict):
            dns_cap_section = {}

            soa_cap_map = dns_section.get("soa_field_cap_map")
            if isinstance(soa_cap_map, dict) and soa_cap_map:
                dns_cap_section["soa_field_cap_map"] = {
                    domain: dict(fields)
                    for domain, fields in soa_cap_map.items()
                    if isinstance(fields, dict) and fields
                }

            dns_cap_map = dns_section.get("dns_cap_map")
            if isinstance(dns_cap_map, dict) and dns_cap_map:
                dns_cap_section["dns_cap_map"] = {
                    domain: dict(issues)
                    for domain, issues in dns_cap_map.items()
                    if isinstance(issues, dict) and issues
                }

            if dns_cap_section:
                if cap_payload.get("dns") != dns_cap_section:
                    cap_payload["dns"] = dns_cap_section
                    updated = True
            elif "dns" in cap_payload:
                cap_payload.pop("dns", None)
                updated = True

        if updated:
            project.cap = cap_payload
            project.save(update_fields=["cap"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("rolodex", "0063_project_cap"),
    ]

    operations = [
        migrations.RunPython(
            populate_project_cap_from_responses, noop
        ),
    ]

