# Generated by Django 4.2 on 2025-11-16 15:10

from django.db import migrations, models
import ghostwriter.rolodex.models


class Migration(migrations.Migration):
    dependencies = [
        ("rolodex", "0089_web_issues_ai_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="scoping",
            field=models.JSONField(
                blank=True,
                default=ghostwriter.rolodex.models.default_project_scoping,
                help_text="Track the selected scoping categories and their sub-options",
            ),
        ),
    ]
