# Generated by Django 4.2 on 2025-11-04 00:16

from django.db import migrations, models


def create_default_grade_risk(apps, schema_editor):
    GradeRiskMapping = apps.get_model("reporting", "GradeRiskMapping")
    default_map = [
        ("A", "low"),
        ("A-", "low"),
        ("B+", "low"),
        ("B", "medium"),
        ("B-", "medium"),
        ("C+", "medium"),
        ("C", "medium"),
        ("C-", "high"),
        ("D+", "high"),
        ("D", "high"),
        ("D-", "high"),
        ("F", "high"),
    ]

    for grade, risk in default_map:
        GradeRiskMapping.objects.update_or_create(grade=grade, defaults={"risk": risk})


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0059_merge_20250409_1340"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeRiskMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B", "B"),
                            ("B-", "B-"),
                            ("C+", "C+"),
                            ("C", "C"),
                            ("C-", "C-"),
                            ("D+", "D+"),
                            ("D", "D"),
                            ("D-", "D-"),
                            ("F", "F"),
                        ],
                        help_text="Letter grade value from uploaded workbooks (e.g., B+ or C-)",
                        max_length=2,
                        unique=True,
                        verbose_name="Letter Grade",
                    ),
                ),
                (
                    "risk",
                    models.CharField(
                        choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                        default="medium",
                        help_text="Risk level that should be associated with this letter grade",
                        max_length=6,
                        verbose_name="Mapped Risk",
                    ),
                ),
            ],
            options={
                "ordering": ["grade"],
                "verbose_name": "Grade to risk mapping",
                "verbose_name_plural": "Grade to risk mappings",
            },
        ),
        migrations.RunPython(create_default_grade_risk, migrations.RunPython.noop),
    ]
