# Generated by Django 4.2 on 2025-11-04 00:17

from django.db import migrations, models


DEFAULT_PASSWORD_COMPLIANCE_MATRIX = {
    "max_age": {
        "data_type": "numeric",
        "rule": {
            "operator": "any",
            "rules": [
                {"operator": "ne", "value": 0},
                {"operator": "lt", "value": 365},
            ],
        },
    },
    "min_age": {
        "data_type": "numeric",
        "rule": {
            "operator": "any",
            "rules": [
                {"operator": "lt", "value": 1},
                {"operator": "gt", "value": 7},
            ],
        },
    },
    "min_length": {
        "data_type": "numeric",
        "rule": {"operator": "lt", "value": 8},
    },
    "history": {
        "data_type": "numeric",
        "rule": {"operator": "lt", "value": 10},
    },
    "lockout_threshold": {
        "data_type": "numeric",
        "rule": {
            "operator": "any",
            "rules": [
                {"operator": "eq", "value": 0},
                {"operator": "gt", "value": 6},
            ],
        },
    },
    "lockout_duration": {
        "data_type": "numeric",
        "rule": {
            "operator": "all",
            "rules": [
                {"operator": "gte", "value": 1},
                {"operator": "lte", "value": 29},
            ],
        },
    },
    "lockout_reset": {
        "data_type": "numeric",
        "rule": {"operator": "lt", "value": 30},
    },
    "complexity_enabled": {
        "data_type": "string",
        "rule": {
            "operator": "any",
            "rules": [
                {"operator": "eq", "value": "TRUE"},
                {"operator": "eq", "value": "YES"},
            ],
        },
    },
}


def seed_password_compliance_matrix(apps, schema_editor):
    mapping_model = apps.get_model("reporting", "PasswordComplianceMapping")
    for setting, definition in DEFAULT_PASSWORD_COMPLIANCE_MATRIX.items():
        mapping_model.objects.update_or_create(
            setting=setting,
            defaults={
                "data_type": definition.get("data_type", "numeric"),
                "rule": definition.get("rule", {}),
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0060_graderiskmapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordComplianceMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("setting", models.CharField(help_text="Name of the password policy setting captured from workbook data.", max_length=64, unique=True, verbose_name="Password setting")),
                ("data_type", models.CharField(choices=[("numeric", "Numeric"), ("string", "String")], default="numeric", help_text="How the policy value should be interpreted when evaluating compliance.", max_length=16, verbose_name="Value type")),
                ("rule", models.JSONField(default=dict, help_text="Definition describing when the password setting is considered out of compliance. Rules may include logical groupings (any/all) and comparison operators.", verbose_name="Non-compliance rule")),
            ],
            options={
                "ordering": ["setting"],
                "verbose_name": "Password setting compliance rule",
                "verbose_name_plural": "Password Setting Compliance matrix",
            },
        ),
        migrations.RunPython(seed_password_compliance_matrix, migrations.RunPython.noop),
    ]
