# Generated by Django 4.2.16 on 2026-10-07 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ghostwriter.reporting.models
import ghostwriter.reporting.validators


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reporting", "0062_reporttemplate_contains_bloodhound_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportSupplementalFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("web", "Web (Burp)"), ("nexpose", "Nexpose")],
                        max_length=32,
                        verbose_name="Kind",
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        max_length=255,
                        upload_to=ghostwriter.reporting.models.set_supplemental_upload_destination,
                        validators=[
                            ghostwriter.reporting.validators.validate_xlsx_extension
                        ],
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Original Filename"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now=True, verbose_name="Uploaded At"),
                ),
                (
                    "cap_entries",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Normalized CAP rows parsed from the workbook",
                        verbose_name="CAP Entries",
                    ),
                ),
                (
                    "row_count",
                    models.PositiveIntegerField(default=0, verbose_name="Row Count"),
                ),
                (
                    "parse_warnings",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Parse Warnings"
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplemental_files",
                        to="reporting.report",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Report supplemental file",
                "verbose_name_plural": "Report supplemental files",
                "ordering": ["report", "kind"],
            },
        ),
        migrations.AddConstraint(
            model_name="reportsupplementalfile",
            constraint=models.UniqueConstraint(
                fields=("report", "kind"),
                name="reporting_supplemental_unique_kind_per_report",
            ),
        ),
    ]
