# Generated by Django 4.2 on 2025-11-17 12:44

from decimal import Decimal

import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


DEFAULT_SCOPING_WEIGHTS = [
    (
        "external",
        "External",
        [
            ("nexpose", "Nexpose", Decimal("0.5")),
            ("web", "Web", Decimal("0.4")),
            ("dns", "DNS", Decimal("0.05")),
            ("osint", "OSINT", Decimal("0.05")),
        ],
    ),
    (
        "internal",
        "Internal",
        [
            ("nexpose", "Nexpose", Decimal("0.5")),
            ("endpoint", "Endpoint", Decimal("0.27")),
            ("snmp", "SNMP", Decimal("0.12")),
            ("sql", "SQL", Decimal("0.11")),
        ],
    ),
    (
        "iam",
        "IAM",
        [("ad", "AD", Decimal("0.6")), ("password", "Password", Decimal("0.4"))],
    ),
    (
        "wireless",
        "Wireless",
        [
            ("walkthru", "Walkthru", Decimal("0.5")),
            ("segmentation", "Segmentation", Decimal("0.5")),
        ],
    ),
    (
        "firewall",
        "Firewall",
        [
            ("configuration", "Configuration", Decimal("0.6")),
            ("os", "OS", Decimal("0.4")),
        ],
    ),
    (
        "cloud",
        "Cloud",
        [
            ("iam_management", "IAM Management", Decimal("0.5")),
            ("cloud_management", "Cloud Management", Decimal("0.5")),
        ],
    ),
]


def seed_scoping_weight_defaults(apps, schema_editor):  # pragma: no cover - migration logic
    Category = apps.get_model("reporting", "ScopingWeightCategory")
    Option = apps.get_model("reporting", "ScopingWeightOption")

    for position, (category_key, category_label, options) in enumerate(
        DEFAULT_SCOPING_WEIGHTS, start=1
    ):
        category, _ = Category.objects.get_or_create(
            key=category_key,
            defaults={"label": category_label, "position": position},
        )
        update_fields = []
        if category.label != category_label:
            category.label = category_label
            update_fields.append("label")
        if category.position != position:
            category.position = position
            update_fields.append("position")
        if update_fields:
            category.save(update_fields=update_fields)

        for option_position, (option_key, option_label, weight) in enumerate(
            options, start=1
        ):
            Option.objects.update_or_create(
                category=category,
                key=option_key,
                defaults={
                    "label": option_label,
                    "weight": weight,
                    "position": option_position,
                },
            )


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0062_riskscorerangemapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScopingWeightCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Identifier that matches keys in the project scoping payload (e.g., external)",
                        max_length=32,
                        unique=True,
                        verbose_name="Category Key",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human-friendly category name",
                        max_length=255,
                        verbose_name="Display Label",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Control how categories and their weights are displayed in the admin",
                        verbose_name="Display Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scoping weight category",
                "verbose_name_plural": "Scoping weight categories",
                "ordering": ["position", "label"],
            },
        ),
        migrations.AlterField(
            model_name="reporttemplate",
            name="document",
            field=models.FileField(
                blank=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location="/workspace/Cyberwriter/ghostwriter/media/templates"
                ),
                upload_to="",
            ),
        ),
        migrations.CreateModel(
            name="ScopingWeightOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Identifier that matches a specific scoping option (e.g., nexpose)",
                        max_length=32,
                        verbose_name="Option Key",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human-friendly option name",
                        max_length=255,
                        verbose_name="Display Label",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Relative weight to use when this option is in scope (values are normalized per category)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Base Weight",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Control how options are listed under their category",
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="reporting.scopingweightcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scoping weight option",
                "verbose_name_plural": "Scoping weight options",
                "ordering": ["category", "position", "label"],
                "unique_together": {("category", "key")},
            },
        ),
        migrations.RunPython(seed_scoping_weight_defaults, migrations.RunPython.noop),
    ]
